# The specified storage capacity is ignored. The PVC is matched with a statically provisoned PV using the volumeName
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: input-volume-claim
spec:
  volumeName: "input-volume"
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5G

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-volume-claim
spec:
  volumeName: "model-volume"
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5G

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archive-volume-claim
spec:
  volumeName: "archive-volume"
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telemetry-volume-claim
spec:
  volumeName: "telemetry-volume"
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outliers-volume-claim
spec:
  volumeName: "outliers-volume"
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
