apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-python
  name: ml-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-python
  template:
    metadata:
      labels:
        app: ml-python
    spec:
      containers:
        - env:
            - name: MODEL
              value: plant-disease-model-complete.pth
            - name: THRESHOLD
              value: "90"
          image: muhammadb/xbu-ml-python:prodv6
          name: ml-python
          volumeMounts:
            - mountPath: /app/inputs/test
              name: input-volume-claim
            - mountPath: /app/models
              name: model-volume-claim
            - mountPath: /app/archive
              name: archive-volume-claim
            - mountPath: /app/telemetry
              name: telemetry-volume-claim
            - mountPath: /app/outliers
              name: outliers-volume-claim
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: input-volume-claim
          persistentVolumeClaim:
            claimName: input-volume-claim
        - name: model-volume-claim
          persistentVolumeClaim:
            claimName: model-volume-claim
        - name: archive-volume-claim
          persistentVolumeClaim:
            claimName: archive-volume-claim
        - name: telemetry-volume-claim
          persistentVolumeClaim:
            claimName: telemetry-volume-claim
        - name: outliers-volume-claim
          persistentVolumeClaim:
            claimName: outliers-volume-claim
            
