apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-python
  name: ml-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-python
  template:
    metadata:
      labels:
        app: ml-python
    spec:
      containers:
        - env:
            - name: MODEL
              value: plant-disease-model-complete.pth
            - name: THRESHOLD
              value: "90"
          image: muhammadb/xbu-ml-python:prodv6
          name: ml-python
          volumeMounts:
            - mountPath: /app/inputs/test
              name: volume_input_claim
            - mountPath: /app/models
              name: volume_model_claim
            - mountPath: /app/archive
              name: volume_archive_claim
            - mountPath: /app/telemetry
              name: volume_telemetry_claim
            - mountPath: /app/outliers
              name: volume_outliers_claim
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: volume_input_claim
          persistentVolumeClaim:
            claimName: volume_input_claim
        - name: volume_model_claim
          persistentVolumeClaim:
            claimName: volume_model_claim
        - name: volume_archive_claim
          persistentVolumeClaim:
            claimName: volume_archive_claim
        - name: volume_telemetry_claim
          persistentVolumeClaim:
            claimName: volume_telemetry_claim
        - name: volume_outliers_claim
          persistentVolumeClaim:
            claimName: volume_outliers_claim
            
