apiVersion: v1
kind: Service
metadata:
  labels:
    app: mqtt
  name: mqtt
spec:
  ports:
    - name: "mqtt-1883-svc"
      port: 1883
      targetPort: 1883
    - name: "mqt-1884-svc"
      port: 1884
      targetPort: 1884
  selector:
    app: mqtt
  type: NodePort
