apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - env:
            - name: CHOKIDAR_USEPOLLING
              value: "true"
          image: muhammadb/xbu-ui:prodv7
          name: ui
          ports:
            - containerPort: 3000
          stdin: true
          volumeMounts:
            - mountPath: /app/inputs/test
              name: input-volume-claim
      imagePullSecrets:
        - name: regcred 
      volumes:
        - name: input-volume-claim
          persistentVolumeClaim:
            claimName: input-volume-claim
